crm/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    
    path('signup/', views.signup_handle, name='signup'),
    path('login/', views.login_handle, name='login'),
    path('logout/', views.logout_handle, name='logout'),
    
    path('user/', views.userProfile, name='user-profile'),
    path('settings/', views.userSettings, name='user-settings'),
    path('products/', views.products, name='products'),
    path('customer/<str:pk>/', views.customer, name='customer'),
    
    path('create_order/<str:pk>', views.createOrder, name='create_order'),
    path('update_order/<str:pk>', views.updateOrder, name='update_order'),
    path('delete_order/<str:pk>', views.deleteOrder, name='delete_order'),
    
    path(
        'reset_password', 
        auth_views.PasswordResetView.as_view(
            template_name='accounts/auth/password_reset.html'
        ),
        name='reset_password'
        ),

    path(
        'reset_password_sent', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/auth/password_reset_done.html'
        ),
        name='password_reset_done'),

    path(
        'reset_password/<uidb64>/<token>', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/auth/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),

    path(
        'reset_password_complete', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/auth/password_reset_complete.html'
        ),
        name='password_reset_complete'
        )

]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=60, null=True)
    phone = models.CharField(max_length=60, null=True)
    email = models.CharField(max_length=60, null=True)
    userpic = models.ImageField(null=True, blank=True, default='default-men.jpg')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Outdoor', 'Outdoor')
    )

    name = models.CharField(max_length=60, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=10, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag')

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=60, null=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for Delivery', 'Out for Delivery'),
        ('Delivered', 'Delivered')
    )
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    note = models.CharField(max_length=1000, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, null=True, choices=STATUS)

    def __str__(self):
        return f'{self.customer}({self.date_created})'

crm/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'py-1 px-1 text-gray-900 outline-none block h-full w-full',
                'autocomplete': 'false',
                'placeholder': 'enter new username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'py-1 px-1 outline-none block h-full w-full',
                'autocomplete': 'false'
            }),
            'phone': forms.TextInput(attrs={
                'class': 'py-1 px-1 outline-none block h-full w-full',
                'autocomplete': 'false'
            }),
            'userpic': forms.FileInput(attrs={

            })
        }

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Confirm'})

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
        }

crm/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from .filters import OrderFilter
from .decorators import unauthenticated_user, allowed_users, admin_only


@login_required(login_url='login')
@admin_only
def home(request):
    customers = Customer.objects.all()
    total_customers = customers.count()
    orders = Order.objects.all()
    total_orders = orders.count()
    orders_pending = orders.filter(status='Pending').count()
    orders_delivered = orders.filter(status='Delivered').count()
    context = {
        'orders': orders, 
        'customers': customers, 
        'orders_total': total_orders,
        'orders_pending': orders_pending,
        'orders_delivered': orders_delivered
        }
    
    return render(request, 'accounts/dashboard.html', context)


@unauthenticated_user
def signup_handle(request): 
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, 'Account was created for ' + username)
            return redirect('login')
    context = {'form': form}
    return render(request, 'accounts/auth/signup.html', context)


@unauthenticated_user
def login_handle(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password =  request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or Password is incorrect')
    return render(request, 'accounts/auth/login.html')


@login_required(login_url='login')
def logout_handle(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
@allowed_users(['admin', 'moderator'])
def products(request):
    products = Product.objects.all()
    return render(request, 'accounts/products.html', {'products': products})


@login_required(login_url='login')
@allowed_users(['admin', 'moderator'])
def customer(request, pk):
    customer = Customer.objects.get(id=pk)
    customer_orders = customer.order_set.all()
    filter_ = OrderFilter(request.GET, queryset=customer_orders)
    customer_orders = filter_.qs
    context = {
        'customer': customer, 
        'orders': customer_orders, 
        'orders_count': customer_orders.count(),
        'filter_': filter_
        }
    return render(request, 'accounts/customer.html', context)


@login_required(login_url='login')
@allowed_users(['admin', 'moderator'])
def createOrder(request, pk):
    OrderFormSet = inlineformset_factory(
        Customer, 
        Order, 
        fields=('product', 'status'), 
        extra=5, 
        can_delete=False
        )
    customer = Customer.objects.get(id=pk)
    formset = OrderFormSet(queryset=Order.objects.none(), instance=customer)

    if request.method == 'POST':
        formset = OrderFormSet(request.POST, instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('/')

    context = {
        'formset': formset
    }

    return render(request, 'accounts/order_form.html', context)


@login_required(login_url='login')
@allowed_users(['admin', 'moderator'])
def updateOrder(request, pk):
    order = Order.objects.get(id=pk)
    form = OrderForm(instance=order)

    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'formset': form
    }

    return render(request, 'accounts/order_form.html', context)


@login_required(login_url='login')
@allowed_users(['admin', 'moderator'])
def deleteOrder(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('/')
    context = {
        'order': order.product.name
    }
    return render(request, 'accounts/delete_form.html', context)


@login_required(login_url='login')
@allowed_users(['customer'])
def userProfile(request):
    user = request.user
    orders = user.customer.order_set.all()
    orders_total = orders.count()
    orders_delivered = orders.filter(status='Delivered').count()
    orders_pending = orders.filter(status='Pending').count()
    context = {
        'user': user, 
        'orders': orders,
        'orders_total': orders_total,
        'orders_delivered': orders_delivered,
        'orders_pending': orders_pending,
        }
    return render(request, 'accounts/user.html', context)


@login_required(login_url='login')
@allowed_users(['customer'])
def userSettings(request):
    customer = request.user.customer
    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
    return render(request, 'accounts/settings.html', {'form': form})

crm/accounts/templates/accounts/customer.html
{% extends 'accounts/main.html' %}

{% block content %}
<div class="row mx-1 my-2">
    <div class="col-md">
        <div class="card card-body">
            <h5>Customer: {{ customer.name }}</h5>
            <hr>
            <a href="" class="btn btn-outline-info btn-sm btn-block">Update Customer</a>
            <a href="{% url 'create_order' customer.id %}" class="btn btn-outline-danger btn-sm btn-block">Place Order</a>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{ customer.email }}</p>
            <p>Phone: {{ customer.phone }}</p>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align: center; padding: 10px;">{{ orders_count }}</h1>
        </div>
    </div>
</div>

<div class="row mx-1 my-2">
    <div class="col-md">
        <div class="card card-body">
            <form method="GET" class='filter-form'>
                {{ filter_.form }}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>        
        </div>
    </div>
</div>

<div class="row mx-1 my-2">
    <div class="col-md">
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Note</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{ order.product }}</td>
                    <td>{{ order.product.category }}</td>
                    <td>{{ order.note }}</td>
                    <td>{{ order.date_created }}</td>
                    <td>{{ order.status }}</td>
                    <td><a href="{% url 'update_order' order.id %}">Update</a></td>
                    <td><a href="{% url 'delete_order' order.id %}">Remove</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

crm/accounts/templates/accounts/dashboard.html
{% extends 'accounts/main.html' %}

{% block content %}

{% include 'accounts\status.html' %}
<div class="row mx-1">
    <div class="col-md-5">
        <h5>Customers</h5>
        <hr>
        <div class="card card-body">
            <a href="" class="btn btn-primary btn-sm btn-block">
                Create Customer
            </a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Customer</th>
                    <th>Orders</th>
                </tr>
                {% for customer in customers %}
                <tr>
                    <td><a href="{% url 'customer' customer.id %}" class="btn btn-info btn-sm">View</a></td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.phone }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-md-7">
        <h5>Last 5 Orders</h5>
        <hr>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{ order.product.name }}</td>
                    <td>{{ order.date_created }}</td>
                    <td>{{ order.status }}</td>
                    <td><a class="btn btn-info btn-sm" href="{% url 'update_order' order.id %}">Update</a></td>
                    <td><a class="btn btn-danger btn-sm" href="{% url 'delete_order' order.id %}">Remove</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

crm/accounts/templates/accounts/delete_form.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to delete {{ order }}?</h3>
    <a href="{% url 'home' %}">Cancel</a>
    <input type="submit" name="Confirm">
</form>
{% endblock %}

crm/accounts/templates/accounts/footer.html
<footer class="text-gray-700 body-font sticky bottom-0">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
      <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">2020 —
        <a href="https://github.com/daslef" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">/daslef</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
      </span>
    </div>
  </footer>

crm/accounts/templates/accounts/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>CRM</title>
</head>
<body class="h-screen flex flex-col justify-start">
    {% include 'accounts/navbar.html' %}
    {% block content %}{% endblock %}
    <hr>
    {% include 'accounts/footer.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

crm/accounts/templates/accounts/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'images/logo.png' %}" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_admin or user.is_staff %}
        <a class="nav-item nav-link active" href="/">Dashboard <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'products' %}">Products</a>
        {% endif %}
      </div>
      <div class="navbar-nav align-items-center">
        <span class="mx-2">{{ request.user }}</span>
        <a href="{% url 'user-settings' %}" class="nav-item nav-link">Settings</a>
        <a href="{% url 'logout' %}" class="nav-item nav-link">Log Out</a>
      </div>
    </div>
  </nav>
<br>

crm/accounts/templates/accounts/order_form.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-center">
    <form class="d-flex flex-column w-50" action="" method="POST">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="card card-body">
                {{ form }}
            </div>
        {% endfor %}
        <input class="btn btn-info mt-3" type="submit" name="Submit">
    </form>    
</div>
{% endblock %}

crm/accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}

{% block content %}
<div class="row mx-2">
    <div class="col-md">
        <div class="card card-header">
            Products
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Price</th>
                </tr>

                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.price }}</td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>
{% endblock %}

crm/accounts/templates/accounts/settings.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<div class="row w-100 align-items-center justify-content-center">
    <div class="col-md-3 mx-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body pb-0">
                <a href="{% url 'user-profile' %}" class="btn btn-info btn-block">Back to Main Page</a>
                <hr>
                <h3 class="card-title text-center">Account Settings</h4>
                <hr>
            </div>
            <div class="card-body pt-0">
                <img src="{{ request.user.customer.userpic.url }}" class="card-img-top" alt="...">
            </div>
        </div>
    </div>
    <div class="col-md-4 mx-4">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="bg-white shadow rounded-lg p-6">
            
            <div class="grid lg:grid-cols-1 gap-6 my-4">
                <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
                    <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
                        <p> <label for="lastname" class="bg-white text-gray-600 px-1">Email *</label> </p>
                    </div>
                    <p>{{ form.email }}</p>
                </div>
            </div>

            <div class="grid lg:grid-cols-2 gap-6">
                <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
                    <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
                        <p> <label for="name" class="bg-white text-gray-600 px-1">Username *</label> </p>
                    </div>
                    <p>{{ form.name }}</p>
                </div>
                <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
                    <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
                        <p><label for="username" class="bg-white text-gray-600 px-1">Phone *</label></p>
                    </div>
                    <p>{{ form.phone }}</p>
                </div>
            </div>

            <div class="grid lg:grid-cols-1 gap-6 my-4">
                <label class="w-100 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue">
                    <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
                    </svg>
                    <span class="mt-2 text-base leading-normal">Select a file</span>
                    <input type='file' name='userpic' accept='image/*' id='id_userpic' class="hidden" />
                </label>
            </div>

            <div class="p-2 w-full">
                <input type="submit" class="flex mx-auto text-white bg-purple-500 border-0 py-2 px-8 focus:outline-none hover:bg-purple-600 rounded text-lg" value="Save">
            </div>
        </div>
    </form>
    </div>
</div>

{% endblock %}

crm/accounts/templates/accounts/status.html
<br>

<div class="row mx-1 mb-2">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-total">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ orders_total }}</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ orders_delivered }}</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ orders_pending }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

crm/accounts/templates/accounts/user.html
{% extends 'accounts/main.html' %}
{% block content %}

<div class="row mx-3 my-2">
    <h3>{{ request.user.username }}'s Profile</h3>
</div>
{% include 'accounts/status.html' %}
<div class="row mx-1 my-2">
    <div class="col-md">
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Note</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{ order.product }}</td>
                    <td>{{ order.product.category }}</td>
                    <td>{{ order.note }}</td>
                    <td>{{ order.date_created }}</td>
                    <td>{{ order.status }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}